const jobs = [
    ['LinkedIn Job Search', 'ZipRecruiter', 'Indeed Hiring Platform', 'Monster', 'Naukri.com', 'Dice', 'Hired', 'CareerBuilder Job Board', 'Glassdoor', 'hackajob', 'cord', 'Circa', 'PowerToFly', 'OfferZen', 'JobStreet', 'Handshake for Employers', 'Flexa', 'Otta', 'JOIN', 'Snagajob', 'Snaphunt', 'Give A Grad A Go', 'Triplebyte', 'Idealist', 'SimplyHired', 'Built In', 'USAJobs', 'Jobcase', 'Pipeline', 'Talent.com'],
    ['RepVue', 'WayUp', 'Untapped', 'Talent Zoo', 'JobBoard.io', 'Haystack', 'Handshake for Education Partners', 'Remotewant', 'TalentPools', 'GeekHunter', 'Job Portal Script', 'Blocket', 'eQuest', 'Careerleaf', 'Chegg Internships', 'Niceboard', 'Product Hunt', 'talent.io', 'Appcast', 'Hubstaff Talent', 'LinkUp', 'PitchMe', 'Comparably by ZoomInfo', 'FlexJobs', 'HR-ON Recruit', 'JobHopin', 'JobTarget', 'Ladders', 'MyDisabilityJobs', 'OnlineJobs.ph'],
    ['Haley Marketing', 'Jobbex', 'JobMatch', 'Juju', 'Nakuri', 'Qureos', 'Vettery', 'Adzuna', 'College Recruiter', 'Coroflot', 'Djangojobs', 'Dribbble Jobs', 'FunctionalJobs', 'GrabJobs', 'HackerTrail', 'HeadHunter.com', 'iHire', 'InfoJobs', 'interviewing.io', 'Jobillico', 'JobPlus', 'JobServe', 'Jobthemes', 'Lensa', 'Madgex', 'Moonlighting', 'Olibr Resourcing Pvt Ltd', 'Seek', 'TechCareers', 'The Mom Project'],
    ['The Muse for Employers', 'Underdog.io', 'Wellfound', 'Apna', 'AuthenticJobs', 'Before You Apply', 'Big.Jobs', 'Career Vault', 'ClearanceJobs', 'Credo', 'Cryptocurrency Jobs', 'Culinary Agents', 'Cuvette Tech', 'DailyRemote', 'DiversityJobs Powered by Circa', 'Dr. Job', 'eZ Jobs', 'Full-Stack Job', 'genvalues', 'Handshake for Custom Services', 'HiringOpps', 'Jabord', 'Jobbatical', 'JobBoardHQ', 'Jobicy', 'JobsInLogistics.com', 'jobsora.com', 'Jobstoday.world', 'Journalism Jobs', 'Kalibrr'],
    ['Landing.jobs', 'leboncoin Emploi Cadres', 'MatchWork', 'Mediabistro', 'Pakistan Jobs', 'Peple', 'Recruiter.com', 'Remotewokr', 'Remotive', 'Skillset', 'SmartHires', 'Snag', 'Stack Overflow Talent', 'Techfynder', 'Tempo', 'Totaljobs', 'TrueRank', 'Virtual OneStop', 'VueJobs', 'We Work Remotely', 'Wiggli', 'Work From Home Jobs', '30 Hour Jobs', '4Scotty', '50skills', '70 Million Jobs', 'Aijobs', 'Aileensoul Jobs', 'Aizenrecruitment', 'AmbitionBox'],
    ['Apply Direct', 'Aspen Technology Labs', 'Atsii', 'Attorney Jobs in USA', 'BEAMSTART', 'Berlin Startup Jobs', 'Boooom', 'Boss Zhipin', 'CakeResume', 'Careerboard', 'CareerCast', 'CareerCast', 'CareerMD', 'Careermine', 'CareerOne', 'Careers Worldwide', 'CareerWaze', 'Chiltern Hill', 'CleverConnect', 'CompanyMatch', 'ConnectIN Jobs Global', 'CreativeHeads.com', 'Crypto Jobs', 'Crypto Jobs List', 'DATAROCKSTARS', 'Daybook', 'Debut', 'Deskhiker', 'Diffr', 'DirectlyApply'],
    ['DistantJob', 'Dockendo', 'EasyJobScript', 'Eduvacancy', 'ejobsitesoftware', 'Employ Diversity', 'EmployeeLink', 'EmploySee', 'Enjoy Mondays', 'Fabskill', 'FactoryFix ATS', 'Fairygodboss', 'Faruse', 'FieldLevel', 'FindANursingJob.com', 'findjobsolutions', 'FindRemoteCareers.com', 'Fitnessjobs.global', 'ForceFinder', 'Founders Careers', 'GetWork', 'Glints', 'GoWorkaBit', 'Gradconnection', 'Guard Arena', 'Gyrojob', 'Habooz', 'Heirizon', 'Highered', 'Hire4X'],
    ['HireAE', 'HireBeen', 'HireOwl', 'Hireplace.it', 'Hirewire', 'Honeypot', 'HotLizard', 'https://www.dhiyo.ai/', 'Husky', 'ICE Recruit', 'IGB Job Posting', 'Industry', 'Infoempleo', 'Inploi', 'Inspire Global Solutions', 'Inten', 'Interview Cracker', 'Jamit', 'Japan Dev', 'Jobberman.com', 'Jobbio', 'JOBDONE', 'Job Engine', 'JobExpress', 'Jobify.pk', 'Jobiqo', 'JOBITT', 'JobOffer.com', 'Jobrapido', 'JobsArabi.net'],
    ['jobsite', 'JobSite Professional', 'Jobsite Script', 'jobsjobsjobs Pty Ltd', 'JobsLab', 'Jobs Lah', 'Jobs Network', 'JobsnProfiles', 'Jobspresso', 'JobStar - Indeed Clone Script', 'Job Today', 'joinsecret.com', 'Joinyfy', 'Jora', 'Juggle.jobs', 'Junoon', 'Karriere', 'Krops', 'Lazyhr.Com', 'Leftronic', 'Legal Recruitment &amp; Job Board', 'LinkCareer', 'Linkjobz.in', 'LocalWise', 'Loopcv', 'Make it in Ukraine', 'Matador Jobs', 'Metahire', 'Naylor Job Board &amp; Career Center', 'NodeFlair'],
    ['NoDesk', 'nPloy', 'NPO.net', 'Ofir', 'Oliv', 'OneWire', 'OnlyTopTalent', 'Outdefine', 'Outforce.ai', 'Outsourcely', 'Parodia', 'Perform Zone', 'PG Jobsite Pro', 'PlaceJobs', 'PlacementIndia.Com', 'Planet Software', 'PowerGrads', 'Prolancer', "Pycoder's Jobs", 'Qualitician', 'QuikrJobs', 'Receptix', 'Recruitdrip', 'Recruitment Exchange', 'RecruitMilitary', 'Recruitology', 'Remotely', 'RemotelyStack', 'Remote OK', 'RemoteWoman'],
    ['Remote Workers', 'Remotewx', 'Roleshare', 'Salesfolks', 'Savanhu', 'SearchBuddy', 'sForce Jobs', 'Shero', 'Shine Globe', 'Simplejobscript', 'Sirvo', 'SkillBooker', 'SkillGigs', 'Smartjobboard', 'Snap.hr', 'Softy Jobs', 'SparkySpot', 'Spur', 'startup.careers', 'Stepstone', 'SucceedSmart, Inc.', 'Superio', 'SwissDevJobs', 'Taggd', 'Talenetic', 'Talentbay', 'Talent finder', 'TalentsHunt.Com', 'Talent Torrent', 'TalentTribe'],
    ['TalentVine', 'Talroo Pro', 'Tapflow', 'teamglide', 'Techintern.io', 'TechKit', 'TechKluster', 'TechSalesJobs.org', 'The Job Auction', 'TheJobNetwork', 'The Outstaff.', 'TitanHouse', 'TopUSAJobs', 'TradesFactor', 'trampos', 'Trexinet', 'TrueJob', 'Unicorn Hunt', 'USJobPlace', 'VanHack', 'VentureLoop', 'vizajobs', 'Volcanic', 'Website Job Board', 'Welcome to the Jungle', 'WiT-ACE', 'WomenWhoCode', 'Workclass', 'Workees', 'Workex'],
    ['Working Not Working', 'Work In Health Tech', 'Workshape', 'Works Hub', 'YM Careers', 'Zelevate', 'Zippia']

]

const J = {
    LinkedIn: "https://www.linkedin.com",
    wuzzuf: "https://wuzzuf.net",
    glassdoor: "https://www.glassdoor.com" ,
    indeed: "https://www.indeed.com",

}